### PR TITLE
Karmabump

### PR DESCRIPTION
**Pull request by totaltrek**
added a bunch of formats for karma points. there's a big hunk of diff that's basically an unindent. next time i'll put all the whitespace changes in a separate cleanup branch.

### CODE REVIEW

**Comment by atuttle** [comment]
No need to put whitespace in a separate branch as long as it's separate commits

**Comment by atuttle** [comment]
I'll defer to @ryanguill to approve since Karma is his baby

**Comment by totaltrek** [comment]
i think it wasn't separate commits. there are problems with trailing text as well.

**Comment by ryanguill** [comment]
you can just keep committing to the branch if you want, you dont have to close and reopen a new pr

**Pull request closed without merging**
